parameters:
    doctrine.dbal.connection_factory.class: Liip\TestFixturesBundle\Factory\ConnectionFactory

doctrine:
    dbal:
        driver: pdo_sqlite
        user: test
        dbname: test
        path: '%kernel.cache_dir%/__DBNAME__.db'
        url: null
        memory: false
