version: '3'
services:
    application:
        container_name: unit_bundle_app
        image: richcongress/php:7.3
        volumes:
            - .:/app:rw,cached
            - ~/.composer:/home/application/.composer:cached
            - ~/.ssh:/home/application/.ssh:cached
        links:
            - mysql:mysql
    mysql:
        container_name: unit_bundle_mysql
        image: richcongress/mysql:mariadb-10.4
        volumes:
            - mysql_data:/var/lib/mysql:rw
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: app_user
            MYSQL_PASSWORD: app_password
            MYSQL_DATABASE: test_database
networks: {}
volumes:
    mysql_data: ~
