version: '3'
services:
    application:
        container_name: unit_bundle_app
        image: richcongress/php:7.3
        volumes:
            - .:/app:rw,cached
            - ~/.composer:/home/application/.composer:cached
            - ~/.ssh:/home/application/.ssh:cached
